<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>2dcb4f91-7d81-4620-b464-3b7ce7caf323</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
	<GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>
	
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.10" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.DataAnnotations" Version="2.2.0" />
    <PackageReference Include="Microsoft.Extensions.Identity.Stores" Version="8.0.10" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.21.0" />
    <PackageReference Include="Serilog" Version="4.1.0" />
    <PackageReference Include="Serilog.AspNetCore" Version="8.0.3" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.9.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ManageEmployees.Domain\ManageEmployees.Domain.csproj" />
    <ProjectReference Include="..\ManageEmployees.Infra.CrossCutting.IoC\ManageEmployees.Infra.CrossCutting.IoC.csproj" />
    <ProjectReference Include="..\ManageEmployees.Infra.Data\ManageEmployees.Infra.Data.csproj" />
    <ProjectReference Include="..\ManageEmployees.Services\ManageEmployees.Services.csproj" />
  </ItemGroup>



</Project>
